apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
type: Opaque
stringData:
  # stringData 让你直接写明文,K8s 存储时自动 base64 编码。
  # (生产里密码应来自外部密钥管理,这里教学简化)
  REDIS_PASSWORD: "labpassword123"